# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/murilo/picoc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/murilo/picoc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/murilo/picoc/CMakeFiles /home/murilo/picoc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/murilo/picoc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named picoc_freertos

# Build rule for target.
picoc_freertos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picoc_freertos
.PHONY : picoc_freertos

# fast build rule for target.
picoc_freertos/fast:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/build
.PHONY : picoc_freertos/fast

#=============================================================================
# Target rules for targets named picoc_unix

# Build rule for target.
picoc_unix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 picoc_unix
.PHONY : picoc_unix

# fast build rule for target.
picoc_unix/fast:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/build
.PHONY : picoc_unix/fast

clibrary.o: clibrary.c.o

.PHONY : clibrary.o

# target to build an object file
clibrary.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/clibrary.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/clibrary.c.o
.PHONY : clibrary.c.o

clibrary.i: clibrary.c.i

.PHONY : clibrary.i

# target to preprocess a source file
clibrary.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/clibrary.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/clibrary.c.i
.PHONY : clibrary.c.i

clibrary.s: clibrary.c.s

.PHONY : clibrary.s

# target to generate assembly for a file
clibrary.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/clibrary.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/clibrary.c.s
.PHONY : clibrary.c.s

cstdlib/ctype.o: cstdlib/ctype.c.o

.PHONY : cstdlib/ctype.o

# target to build an object file
cstdlib/ctype.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/ctype.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/ctype.c.o
.PHONY : cstdlib/ctype.c.o

cstdlib/ctype.i: cstdlib/ctype.c.i

.PHONY : cstdlib/ctype.i

# target to preprocess a source file
cstdlib/ctype.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/ctype.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/ctype.c.i
.PHONY : cstdlib/ctype.c.i

cstdlib/ctype.s: cstdlib/ctype.c.s

.PHONY : cstdlib/ctype.s

# target to generate assembly for a file
cstdlib/ctype.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/ctype.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/ctype.c.s
.PHONY : cstdlib/ctype.c.s

cstdlib/errno.o: cstdlib/errno.c.o

.PHONY : cstdlib/errno.o

# target to build an object file
cstdlib/errno.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/errno.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/errno.c.o
.PHONY : cstdlib/errno.c.o

cstdlib/errno.i: cstdlib/errno.c.i

.PHONY : cstdlib/errno.i

# target to preprocess a source file
cstdlib/errno.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/errno.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/errno.c.i
.PHONY : cstdlib/errno.c.i

cstdlib/errno.s: cstdlib/errno.c.s

.PHONY : cstdlib/errno.s

# target to generate assembly for a file
cstdlib/errno.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/errno.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/errno.c.s
.PHONY : cstdlib/errno.c.s

cstdlib/math.o: cstdlib/math.c.o

.PHONY : cstdlib/math.o

# target to build an object file
cstdlib/math.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/math.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/math.c.o
.PHONY : cstdlib/math.c.o

cstdlib/math.i: cstdlib/math.c.i

.PHONY : cstdlib/math.i

# target to preprocess a source file
cstdlib/math.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/math.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/math.c.i
.PHONY : cstdlib/math.c.i

cstdlib/math.s: cstdlib/math.c.s

.PHONY : cstdlib/math.s

# target to generate assembly for a file
cstdlib/math.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/math.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/math.c.s
.PHONY : cstdlib/math.c.s

cstdlib/stdbool.o: cstdlib/stdbool.c.o

.PHONY : cstdlib/stdbool.o

# target to build an object file
cstdlib/stdbool.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdbool.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdbool.c.o
.PHONY : cstdlib/stdbool.c.o

cstdlib/stdbool.i: cstdlib/stdbool.c.i

.PHONY : cstdlib/stdbool.i

# target to preprocess a source file
cstdlib/stdbool.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdbool.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdbool.c.i
.PHONY : cstdlib/stdbool.c.i

cstdlib/stdbool.s: cstdlib/stdbool.c.s

.PHONY : cstdlib/stdbool.s

# target to generate assembly for a file
cstdlib/stdbool.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdbool.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdbool.c.s
.PHONY : cstdlib/stdbool.c.s

cstdlib/stdio.o: cstdlib/stdio.c.o

.PHONY : cstdlib/stdio.o

# target to build an object file
cstdlib/stdio.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdio.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdio.c.o
.PHONY : cstdlib/stdio.c.o

cstdlib/stdio.i: cstdlib/stdio.c.i

.PHONY : cstdlib/stdio.i

# target to preprocess a source file
cstdlib/stdio.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdio.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdio.c.i
.PHONY : cstdlib/stdio.c.i

cstdlib/stdio.s: cstdlib/stdio.c.s

.PHONY : cstdlib/stdio.s

# target to generate assembly for a file
cstdlib/stdio.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdio.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdio.c.s
.PHONY : cstdlib/stdio.c.s

cstdlib/stdlib.o: cstdlib/stdlib.c.o

.PHONY : cstdlib/stdlib.o

# target to build an object file
cstdlib/stdlib.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdlib.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdlib.c.o
.PHONY : cstdlib/stdlib.c.o

cstdlib/stdlib.i: cstdlib/stdlib.c.i

.PHONY : cstdlib/stdlib.i

# target to preprocess a source file
cstdlib/stdlib.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdlib.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdlib.c.i
.PHONY : cstdlib/stdlib.c.i

cstdlib/stdlib.s: cstdlib/stdlib.c.s

.PHONY : cstdlib/stdlib.s

# target to generate assembly for a file
cstdlib/stdlib.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/stdlib.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/stdlib.c.s
.PHONY : cstdlib/stdlib.c.s

cstdlib/string.o: cstdlib/string.c.o

.PHONY : cstdlib/string.o

# target to build an object file
cstdlib/string.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/string.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/string.c.o
.PHONY : cstdlib/string.c.o

cstdlib/string.i: cstdlib/string.c.i

.PHONY : cstdlib/string.i

# target to preprocess a source file
cstdlib/string.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/string.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/string.c.i
.PHONY : cstdlib/string.c.i

cstdlib/string.s: cstdlib/string.c.s

.PHONY : cstdlib/string.s

# target to generate assembly for a file
cstdlib/string.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/string.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/string.c.s
.PHONY : cstdlib/string.c.s

cstdlib/time.o: cstdlib/time.c.o

.PHONY : cstdlib/time.o

# target to build an object file
cstdlib/time.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/time.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/time.c.o
.PHONY : cstdlib/time.c.o

cstdlib/time.i: cstdlib/time.c.i

.PHONY : cstdlib/time.i

# target to preprocess a source file
cstdlib/time.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/time.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/time.c.i
.PHONY : cstdlib/time.c.i

cstdlib/time.s: cstdlib/time.c.s

.PHONY : cstdlib/time.s

# target to generate assembly for a file
cstdlib/time.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/time.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/time.c.s
.PHONY : cstdlib/time.c.s

cstdlib/unistd.o: cstdlib/unistd.c.o

.PHONY : cstdlib/unistd.o

# target to build an object file
cstdlib/unistd.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/unistd.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/unistd.c.o
.PHONY : cstdlib/unistd.c.o

cstdlib/unistd.i: cstdlib/unistd.c.i

.PHONY : cstdlib/unistd.i

# target to preprocess a source file
cstdlib/unistd.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/unistd.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/unistd.c.i
.PHONY : cstdlib/unistd.c.i

cstdlib/unistd.s: cstdlib/unistd.c.s

.PHONY : cstdlib/unistd.s

# target to generate assembly for a file
cstdlib/unistd.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/cstdlib/unistd.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/cstdlib/unistd.c.s
.PHONY : cstdlib/unistd.c.s

debug.o: debug.c.o

.PHONY : debug.o

# target to build an object file
debug.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/debug.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/debug.c.o
.PHONY : debug.c.o

debug.i: debug.c.i

.PHONY : debug.i

# target to preprocess a source file
debug.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/debug.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/debug.c.i
.PHONY : debug.c.i

debug.s: debug.c.s

.PHONY : debug.s

# target to generate assembly for a file
debug.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/debug.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/debug.c.s
.PHONY : debug.c.s

expression.o: expression.c.o

.PHONY : expression.o

# target to build an object file
expression.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/expression.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/expression.c.o
.PHONY : expression.c.o

expression.i: expression.c.i

.PHONY : expression.i

# target to preprocess a source file
expression.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/expression.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/expression.c.i
.PHONY : expression.c.i

expression.s: expression.c.s

.PHONY : expression.s

# target to generate assembly for a file
expression.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/expression.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/expression.c.s
.PHONY : expression.c.s

heap.o: heap.c.o

.PHONY : heap.o

# target to build an object file
heap.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/heap.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/heap.c.o
.PHONY : heap.c.o

heap.i: heap.c.i

.PHONY : heap.i

# target to preprocess a source file
heap.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/heap.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/heap.c.i
.PHONY : heap.c.i

heap.s: heap.c.s

.PHONY : heap.s

# target to generate assembly for a file
heap.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/heap.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/heap.c.s
.PHONY : heap.c.s

include.o: include.c.o

.PHONY : include.o

# target to build an object file
include.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/include.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/include.c.o
.PHONY : include.c.o

include.i: include.c.i

.PHONY : include.i

# target to preprocess a source file
include.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/include.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/include.c.i
.PHONY : include.c.i

include.s: include.c.s

.PHONY : include.s

# target to generate assembly for a file
include.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/include.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/include.c.s
.PHONY : include.c.s

lex.o: lex.c.o

.PHONY : lex.o

# target to build an object file
lex.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/lex.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/lex.c.o
.PHONY : lex.c.o

lex.i: lex.c.i

.PHONY : lex.i

# target to preprocess a source file
lex.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/lex.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/lex.c.i
.PHONY : lex.c.i

lex.s: lex.c.s

.PHONY : lex.s

# target to generate assembly for a file
lex.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/lex.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/lex.c.s
.PHONY : lex.c.s

parse.o: parse.c.o

.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/parse.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i

.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/parse.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s

.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/parse.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/parse.c.s
.PHONY : parse.c.s

picoc.o: picoc.c.o

.PHONY : picoc.o

# target to build an object file
picoc.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/picoc.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/picoc.c.o
.PHONY : picoc.c.o

picoc.i: picoc.c.i

.PHONY : picoc.i

# target to preprocess a source file
picoc.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/picoc.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/picoc.c.i
.PHONY : picoc.c.i

picoc.s: picoc.c.s

.PHONY : picoc.s

# target to generate assembly for a file
picoc.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/picoc.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/picoc.c.s
.PHONY : picoc.c.s

platform.o: platform.c.o

.PHONY : platform.o

# target to build an object file
platform.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform.c.o
.PHONY : platform.c.o

platform.i: platform.c.i

.PHONY : platform.i

# target to preprocess a source file
platform.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform.c.i
.PHONY : platform.c.i

platform.s: platform.c.s

.PHONY : platform.s

# target to generate assembly for a file
platform.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform.c.s
.PHONY : platform.c.s

platform/library_freertos.o: platform/library_freertos.c.o

.PHONY : platform/library_freertos.o

# target to build an object file
platform/library_freertos.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/library_freertos.c.o
.PHONY : platform/library_freertos.c.o

platform/library_freertos.i: platform/library_freertos.c.i

.PHONY : platform/library_freertos.i

# target to preprocess a source file
platform/library_freertos.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/library_freertos.c.i
.PHONY : platform/library_freertos.c.i

platform/library_freertos.s: platform/library_freertos.c.s

.PHONY : platform/library_freertos.s

# target to generate assembly for a file
platform/library_freertos.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/library_freertos.c.s
.PHONY : platform/library_freertos.c.s

platform/library_unix.o: platform/library_unix.c.o

.PHONY : platform/library_unix.o

# target to build an object file
platform/library_unix.c.o:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/library_unix.c.o
.PHONY : platform/library_unix.c.o

platform/library_unix.i: platform/library_unix.c.i

.PHONY : platform/library_unix.i

# target to preprocess a source file
platform/library_unix.c.i:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/library_unix.c.i
.PHONY : platform/library_unix.c.i

platform/library_unix.s: platform/library_unix.c.s

.PHONY : platform/library_unix.s

# target to generate assembly for a file
platform/library_unix.c.s:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/library_unix.c.s
.PHONY : platform/library_unix.c.s

platform/platform_freertos.o: platform/platform_freertos.c.o

.PHONY : platform/platform_freertos.o

# target to build an object file
platform/platform_freertos.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/platform_freertos.c.o
.PHONY : platform/platform_freertos.c.o

platform/platform_freertos.i: platform/platform_freertos.c.i

.PHONY : platform/platform_freertos.i

# target to preprocess a source file
platform/platform_freertos.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/platform_freertos.c.i
.PHONY : platform/platform_freertos.c.i

platform/platform_freertos.s: platform/platform_freertos.c.s

.PHONY : platform/platform_freertos.s

# target to generate assembly for a file
platform/platform_freertos.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/platform/platform_freertos.c.s
.PHONY : platform/platform_freertos.c.s

platform/platform_unix.o: platform/platform_unix.c.o

.PHONY : platform/platform_unix.o

# target to build an object file
platform/platform_unix.c.o:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/platform_unix.c.o
.PHONY : platform/platform_unix.c.o

platform/platform_unix.i: platform/platform_unix.c.i

.PHONY : platform/platform_unix.i

# target to preprocess a source file
platform/platform_unix.c.i:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/platform_unix.c.i
.PHONY : platform/platform_unix.c.i

platform/platform_unix.s: platform/platform_unix.c.s

.PHONY : platform/platform_unix.s

# target to generate assembly for a file
platform/platform_unix.c.s:
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/platform/platform_unix.c.s
.PHONY : platform/platform_unix.c.s

table.o: table.c.o

.PHONY : table.o

# target to build an object file
table.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/table.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/table.c.o
.PHONY : table.c.o

table.i: table.c.i

.PHONY : table.i

# target to preprocess a source file
table.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/table.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/table.c.i
.PHONY : table.c.i

table.s: table.c.s

.PHONY : table.s

# target to generate assembly for a file
table.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/table.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/table.c.s
.PHONY : table.c.s

type.o: type.c.o

.PHONY : type.o

# target to build an object file
type.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/type.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/type.c.o
.PHONY : type.c.o

type.i: type.c.i

.PHONY : type.i

# target to preprocess a source file
type.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/type.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/type.c.i
.PHONY : type.c.i

type.s: type.c.s

.PHONY : type.s

# target to generate assembly for a file
type.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/type.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/type.c.s
.PHONY : type.c.s

variable.o: variable.c.o

.PHONY : variable.o

# target to build an object file
variable.c.o:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/variable.c.o
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/variable.c.o
.PHONY : variable.c.o

variable.i: variable.c.i

.PHONY : variable.i

# target to preprocess a source file
variable.c.i:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/variable.c.i
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/variable.c.i
.PHONY : variable.c.i

variable.s: variable.c.s

.PHONY : variable.s

# target to generate assembly for a file
variable.c.s:
	$(MAKE) -f CMakeFiles/picoc_freertos.dir/build.make CMakeFiles/picoc_freertos.dir/variable.c.s
	$(MAKE) -f CMakeFiles/picoc_unix.dir/build.make CMakeFiles/picoc_unix.dir/variable.c.s
.PHONY : variable.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... picoc_freertos"
	@echo "... picoc_unix"
	@echo "... clibrary.o"
	@echo "... clibrary.i"
	@echo "... clibrary.s"
	@echo "... cstdlib/ctype.o"
	@echo "... cstdlib/ctype.i"
	@echo "... cstdlib/ctype.s"
	@echo "... cstdlib/errno.o"
	@echo "... cstdlib/errno.i"
	@echo "... cstdlib/errno.s"
	@echo "... cstdlib/math.o"
	@echo "... cstdlib/math.i"
	@echo "... cstdlib/math.s"
	@echo "... cstdlib/stdbool.o"
	@echo "... cstdlib/stdbool.i"
	@echo "... cstdlib/stdbool.s"
	@echo "... cstdlib/stdio.o"
	@echo "... cstdlib/stdio.i"
	@echo "... cstdlib/stdio.s"
	@echo "... cstdlib/stdlib.o"
	@echo "... cstdlib/stdlib.i"
	@echo "... cstdlib/stdlib.s"
	@echo "... cstdlib/string.o"
	@echo "... cstdlib/string.i"
	@echo "... cstdlib/string.s"
	@echo "... cstdlib/time.o"
	@echo "... cstdlib/time.i"
	@echo "... cstdlib/time.s"
	@echo "... cstdlib/unistd.o"
	@echo "... cstdlib/unistd.i"
	@echo "... cstdlib/unistd.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... expression.o"
	@echo "... expression.i"
	@echo "... expression.s"
	@echo "... heap.o"
	@echo "... heap.i"
	@echo "... heap.s"
	@echo "... include.o"
	@echo "... include.i"
	@echo "... include.s"
	@echo "... lex.o"
	@echo "... lex.i"
	@echo "... lex.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... picoc.o"
	@echo "... picoc.i"
	@echo "... picoc.s"
	@echo "... platform.o"
	@echo "... platform.i"
	@echo "... platform.s"
	@echo "... platform/library_freertos.o"
	@echo "... platform/library_freertos.i"
	@echo "... platform/library_freertos.s"
	@echo "... platform/library_unix.o"
	@echo "... platform/library_unix.i"
	@echo "... platform/library_unix.s"
	@echo "... platform/platform_freertos.o"
	@echo "... platform/platform_freertos.i"
	@echo "... platform/platform_freertos.s"
	@echo "... platform/platform_unix.o"
	@echo "... platform/platform_unix.i"
	@echo "... platform/platform_unix.s"
	@echo "... table.o"
	@echo "... table.i"
	@echo "... table.s"
	@echo "... type.o"
	@echo "... type.i"
	@echo "... type.s"
	@echo "... variable.o"
	@echo "... variable.i"
	@echo "... variable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

